name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ravikantchauhan/laravel:latest

    - name: Push the Docker image to Docker Hub
      run: |
        docker login -u ravikantchauhan -p ${{ secrets.DOH }}
        docker push ravikantchauhan/laravel:latest
