name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "dckr_pat_Ro-dj2DQ5eKNDhx0nMnTb1-xDmk" | docker login -u "ravikantchauhan" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ravikantchauhan/laravel:latest

    - name: Push the Docker image to Docker Hub
      run: docker push ravikantchauhan/laravel:latest
